# Generated by Django 2.0.3 on 2018-03-21 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Persion',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('sql_order', models.IntegerField()),
            ],
            options={
                'db_table': 'my_self_persion',
                'ordering': ('-sql_order',),
            },
        ),
    ]
